# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codemetagenerator < Formula
  desc "A CodeMeta project description generator written in Go."
  homepage "https://angstrom.io/codemetagenerator"
  version "0.47.11"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/cacoco/codemetagenerator/releases/download/v0.47.11/codemetagenerator_Darwin_all.tar.gz", using: CurlDownloadStrategy
    sha256 "b17bda929b09a9968d4b3cfe30669b6a83cabbe5d8cbed3f2ef42379fa6a380c"

    def install
      bin.install "codemetagenerator"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cacoco/codemetagenerator/releases/download/v0.47.11/codemetagenerator_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "b4cf95dc163f78c4b0d12cff2ed9754e4d44f630858fb2ddf3a705c46f6bc97c"

      def install
        bin.install "codemetagenerator"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/cacoco/codemetagenerator/releases/download/v0.47.11/codemetagenerator_Linux_armv7.tar.gz", using: CurlDownloadStrategy
      sha256 "cf5bb5dce73443b5275fd298833360a5dc2eb7bd134c6efea038fb9c51a82b7e"

      def install
        bin.install "codemetagenerator"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cacoco/codemetagenerator/releases/download/v0.47.11/codemetagenerator_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "a3b1b70dea769d7eb2a74ec45ac4a414b2191a15ebde8dd61a17d819f8f8681f"

      def install
        bin.install "codemetagenerator"
      end
    end
  end
end
