# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codemetagenerator < Formula
  desc "A CodeMeta project description generator written in Go."
  homepage "https://angstrom.io/codemetagenerator"
  version "0.47.7"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/cacoco/codemetagenerator/releases/download/v0.47.7/codemetagenerator_Darwin_all.tar.gz", using: CurlDownloadStrategy
    sha256 "f43452ba1729e2c1033a002794c87a946e7b92bbd16df310b74c95f9fc9ff241"

    def install
      bin.install "codemetagenerator"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cacoco/codemetagenerator/releases/download/v0.47.7/codemetagenerator_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "0ff40ddfb733257a01b09de5765ead59b7f7255f164761fd8338adeccc613b69"

      def install
        bin.install "codemetagenerator"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/cacoco/codemetagenerator/releases/download/v0.47.7/codemetagenerator_Linux_armv7.tar.gz", using: CurlDownloadStrategy
      sha256 "a0e50e3c26327640675a6d09bad2267487c276f77898b342761adce8da790b1b"

      def install
        bin.install "codemetagenerator"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cacoco/codemetagenerator/releases/download/v0.47.7/codemetagenerator_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "31865351f9b471c468d0c26b88a2b17e4434eee224024bd9b7a2e79e7104e238"

      def install
        bin.install "codemetagenerator"
      end
    end
  end
end
